//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainHub.Internal.PeopleAndCulture.PartnerManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainHub.Internal.PeopleAndCulture.PartnerManagement.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Date.
        /// </summary>
        public static string ActionDate {
            get {
                return ResourceManager.GetString("ActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed Action.
        /// </summary>
        public static string ActionFailed {
            get {
                return ResourceManager.GetString("ActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address Information.
        /// </summary>
        public static string AddressInformation {
            get {
                return ResourceManager.GetString("AddressInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Deleted with success.
        /// </summary>
        public static string ApproveDeleteContact {
            get {
                return ResourceManager.GetString("ApproveDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirects to the previous page.
        /// </summary>
        public static string BackTtp {
            get {
                return ResourceManager.GetString("BackTtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string ButtonSubmit {
            get {
                return ResourceManager.GetString("ButtonSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Search.
        /// </summary>
        public static string CancelSearch {
            get {
                return ResourceManager.GetString("CancelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account.
        /// </summary>
        public static string ChangeAccount {
            get {
                return ResourceManager.GetString("ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed Date.
        /// </summary>
        public static string ChangedDate {
            get {
                return ResourceManager.GetString("ChangedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string CloseTtp {
            get {
                return ResourceManager.GetString("CloseTtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact successfully edited!.
        /// </summary>
        public static string ContactApproved {
            get {
                return ResourceManager.GetString("ContactApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Creation.
        /// </summary>
        public static string ContactCreation {
            get {
                return ResourceManager.GetString("ContactCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string ContactDecide {
            get {
                return ResourceManager.GetString("ContactDecide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will cause the contact belonging to the partner of the current context to be deleted!.
        /// </summary>
        public static string ContactDelete {
            get {
                return ResourceManager.GetString("ContactDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Detail.
        /// </summary>
        public static string ContactDetail {
            get {
                return ResourceManager.GetString("ContactDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact History.
        /// </summary>
        public static string ContactHistory {
            get {
                return ResourceManager.GetString("ContactHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Information.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search contact name.
        /// </summary>
        public static string ContactListSearch {
            get {
                return ResourceManager.GetString("ContactListSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact Menu.
        /// </summary>
        public static string ContactMenu {
            get {
                return ResourceManager.GetString("ContactMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was a problem editing the contact.
        /// </summary>
        public static string ContactNotApproved {
            get {
                return ResourceManager.GetString("ContactNotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redirects to the contact creation form.
        /// </summary>
        public static string ContactRedirectTtp {
            get {
                return ResourceManager.GetString("ContactRedirectTtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact created successfuly!.
        /// </summary>
        public static string ContactRequest {
            get {
                return ResourceManager.GetString("ContactRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts List.
        /// </summary>
        public static string ContactsList {
            get {
                return ResourceManager.GetString("ContactsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Contact.
        /// </summary>
        public static string CreateContact {
            get {
                return ResourceManager.GetString("CreateContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Partner.
        /// </summary>
        public static string CreatePartner {
            get {
                return ResourceManager.GetString("CreatePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erases all data belonged to the current Partner and himself.
        /// </summary>
        public static string DeleteTtp {
            get {
                return ResourceManager.GetString("DeleteTtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        public static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggles the edit mode.
        /// </summary>
        public static string EditTtp {
            get {
                return ResourceManager.GetString("EditTtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an Address..
        /// </summary>
        public static string EnterAddress {
            get {
                return ResourceManager.GetString("EnterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Country..
        /// </summary>
        public static string EnterCountry {
            get {
                return ResourceManager.GetString("EnterCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a department.
        /// </summary>
        public static string EnterDepartment {
            get {
                return ResourceManager.GetString("EnterDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an email.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Locality..
        /// </summary>
        public static string EnterLocality {
            get {
                return ResourceManager.GetString("EnterLocality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Name..
        /// </summary>
        public static string EnterName {
            get {
                return ResourceManager.GetString("EnterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter an Observation..
        /// </summary>
        public static string EnterObservation {
            get {
                return ResourceManager.GetString("EnterObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a observation.
        /// </summary>
        public static string EnterObservationn {
            get {
                return ResourceManager.GetString("EnterObservationn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a phone number.
        /// </summary>
        public static string EnterPhoneNum {
            get {
                return ResourceManager.GetString("EnterPhoneNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Phone Number..
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Postal code..
        /// </summary>
        public static string EnterPostalCode {
            get {
                return ResourceManager.GetString("EnterPostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a role.
        /// </summary>
        public static string EnterRole {
            get {
                return ResourceManager.GetString("EnterRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Service Description..
        /// </summary>
        public static string EnterService {
            get {
                return ResourceManager.GetString("EnterService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a Tax Number..
        /// </summary>
        public static string EnterTaxNumber {
            get {
                return ResourceManager.GetString("EnterTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will erase all Partner Data associated! You want to proceed?.
        /// </summary>
        public static string EraseAllDataPartner {
            get {
                return ResourceManager.GetString("EraseAllDataPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will erase the current Partner! You want to proceed?.
        /// </summary>
        public static string ErasePartner {
            get {
                return ResourceManager.GetString("ErasePartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete the Contact.
        /// </summary>
        public static string ErrorDeleteContact {
            get {
                return ResourceManager.GetString("ErrorDeleteContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clock button lets you show the history!.
        /// </summary>
        public static string HelpTtp {
            get {
                return ResourceManager.GetString("HelpTtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View history.
        /// </summary>
        public static string HistoryTtp {
            get {
                return ResourceManager.GetString("HistoryTtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert information, so that the contact can be edited!.
        /// </summary>
        public static string InsertContact {
            get {
                return ResourceManager.GetString("InsertContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email format.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number format..
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid tax number format..
        /// </summary>
        public static string InvalidTaxNumber {
            get {
                return ResourceManager.GetString("InvalidTaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Contact Info....
        /// </summary>
        public static string LoadingContactInfo {
            get {
                return ResourceManager.GetString("LoadingContactInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Partner....
        /// </summary>
        public static string LoadingPartner {
            get {
                return ResourceManager.GetString("LoadingPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Partner Information...
        /// </summary>
        public static string LoadingPartnerInfo {
            get {
                return ResourceManager.GetString("LoadingPartnerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Profile.
        /// </summary>
        public static string LoadingProfile {
            get {
                return ResourceManager.GetString("LoadingProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to are missing,.
        /// </summary>
        public static string Missing {
            get {
                return ResourceManager.GetString("Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this content..
        /// </summary>
        public static string NoAccess {
            get {
                return ResourceManager.GetString("NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Recent Actions.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find any data.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information.
        /// </summary>
        public static string NoInfo {
            get {
                return ResourceManager.GetString("NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no information about this Partner.
        /// </summary>
        public static string NoPartnerInfo {
            get {
                return ResourceManager.GetString("NoPartnerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Authorized.
        /// </summary>
        public static string NotAuthorized {
            get {
                return ResourceManager.GetString("NotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation.
        /// </summary>
        public static string Observation {
            get {
                return ResourceManager.GetString("Observation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner.
        /// </summary>
        public static string Partner {
            get {
                return ResourceManager.GetString("Partner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Creation.
        /// </summary>
        public static string PartnerCreation {
            get {
                return ResourceManager.GetString("PartnerCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Dates.
        /// </summary>
        public static string PartnerDates {
            get {
                return ResourceManager.GetString("PartnerDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner editted with success.
        /// </summary>
        public static string PartnerEditted {
            get {
                return ResourceManager.GetString("PartnerEditted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A problem occurred while creating the partner.
        /// </summary>
        public static string PartnerError {
            get {
                return ResourceManager.GetString("PartnerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner History.
        /// </summary>
        public static string PartnerHistory {
            get {
                return ResourceManager.GetString("PartnerHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Information.
        /// </summary>
        public static string PartnerInformation {
            get {
                return ResourceManager.GetString("PartnerInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner Menu.
        /// </summary>
        public static string PartnerMenu {
            get {
                return ResourceManager.GetString("PartnerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners Description.
        /// </summary>
        public static string PartnersDescription {
            get {
                return ResourceManager.GetString("PartnersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partners List.
        /// </summary>
        public static string PartnersList {
            get {
                return ResourceManager.GetString("PartnersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string PartnersListAddress {
            get {
                return ResourceManager.GetString("PartnersListAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string PartnersListCountry {
            get {
                return ResourceManager.GetString("PartnersListCountry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string PartnersListName {
            get {
                return ResourceManager.GetString("PartnersListName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search partner name.
        /// </summary>
        public static string PartnersListSearch {
            get {
                return ResourceManager.GetString("PartnersListSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Description.
        /// </summary>
        public static string PartnersListServiceDescription {
            get {
                return ResourceManager.GetString("PartnersListServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Partner created successfuly!.
        /// </summary>
        public static string PartnerSuccess {
            get {
                return ResourceManager.GetString("PartnerSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please insert data.
        /// </summary>
        public static string Please {
            get {
                return ResourceManager.GetString("Please", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert data to edit the partner!.
        /// </summary>
        public static string PleaseInsert {
            get {
                return ResourceManager.GetString("PleaseInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert data, so the contact can be created!.
        /// </summary>
        public static string PleaseInsertRequestContact {
            get {
                return ResourceManager.GetString("PleaseInsertRequestContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please insert data, so the partner can be created!.
        /// </summary>
        public static string PleaseInsertRequestPartner {
            get {
                return ResourceManager.GetString("PleaseInsertRequestPartner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By Mainhub.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        public static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves the data.
        /// </summary>
        public static string SaveTtp {
            get {
                return ResourceManager.GetString("SaveTtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignIn {
            get {
                return ResourceManager.GetString("SignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click to view Partner information!.
        /// </summary>
        public static string ToolTipPartnerList {
            get {
                return ResourceManager.GetString("ToolTipPartnerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click to view Contact information!.
        /// </summary>
        public static string TtpContactList {
            get {
                return ResourceManager.GetString("TtpContactList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guid.
        /// </summary>
        public static string UserGuid {
            get {
                return ResourceManager.GetString("UserGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Principal Name.
        /// </summary>
        public static string UserPrincipalName {
            get {
                return ResourceManager.GetString("UserPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Contacts.
        /// </summary>
        public static string ViewContacts {
            get {
                return ResourceManager.GetString("ViewContacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows you to see all contacts of this partner.
        /// </summary>
        public static string ViewContactTtp {
            get {
                return ResourceManager.GetString("ViewContactTtp", resourceCulture);
            }
        }
    }
}
