# Main Hub - Innovation, Incubation & Development®
# https://www.mainhub.pt/  
# -----------------------------------------------------------------------------
# Azure Devops Pipeline
# -----------------------------------------------------------------------------
# Daily pipeline, to do SCA/SAST analisys. 
# This pipeline is executed on branch "main"/"dev".
#
# Every other location, it will not be executed.
# -----------------------------------------------------------------------------

name: "Daily-Analisys-Pipeline"
schedules:
  - cron: "0 0 * * *"
    displayName: "Daily midnight build"
    branches:
      include:
        - "main"
        - "master"
        - "develop"
trigger: none

pool:
  vmImage: ubuntu-latest

variables: 
  buildConfiguration: "Release"
  solutionFileName: "MainHub.Internal.Internship.PeopleAndCulture"
  majorVersion: "1"
  minorVersion: "0"
  patchVersion: "0"
  artifactVersion: "$(majorVersion).$(minorVersion).$(patchVersion).$(BUILD_BUILDNUMBER)"
  solutionFile: "./$(solutionFileName).sln"
  artifactName: "$(solutionFileName)-drop"

parameters:
  - name: clean
    displayName: Checkout clean
    type: boolean
    default: "false"
    values:
      - "false"
      - "true"

workspace:
  clean: all

steps:
  # ------------------------------
  # Repository Checkout
  # ------------------------------
  - checkout: self
    displayName: "Repository Checkout."
    clean: "true"

  # ------------------------------
  # Install .NET 6 SDK
  # ------------------------------
  - task: UseDotNet@2
    displayName: "Install .NET 6 SDK."
    inputs:
      packageType: 'sdk'
      version: '6.0.407'
      performMultiLevelLookup: true

  # ------------------------------
  # Restoring nuget packages
  # ------------------------------
  - task: DotNetCoreCLI@2
    displayName: "Restoring nuget packages."
    inputs:
      command: 'restore'
      projects: '$(solutionFile)'
      feedsToUse: 'config'
      nugetConfigPath: './nuget.config'
  
  # ------------------------------
  # Building Solution
  # ------------------------------
  - task: DotNetCoreCLI@2
    displayName: "Building Solution."
    inputs:
      command: build
      projects: "$(solutionFile)"
      arguments: "--configuration $(buildConfiguration)"
  
  # ------------------------------
  # SAST (Snyk)  Source Code Analisys
  # ------------------------------
  - task: SnykSecurityScan@1
    displayName: "SAST (Snyk)  Source Code Analisys."
    inputs:
      serviceConnectionEndpoint: 'Main Hub Snyk Service Connection-MainHub.Internal.Internship.PeopleAndCulture'
      testType: 'app'
      monitorWhen: 'always'
      failOnIssues: true
      organization: 'pmainhub.pt'
      additionalArguments: '--all-projects --exclude=test'

  # ------------------------------
  # SAST (White Source)  Source Code Analisys
  # ------------------------------
  - task: WhiteSource@21
    displayName: "SAST (White Source)  Source Code Analisys."
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'
      projectName: 'MainHub.Internal.Internship.PeopleAndCulture'
  
  # ------------------------------
  # SCA (Dependency Check) Third Party Dependencies Analisys
  # ------------------------------
  - task: dependency-check-build-task@6
    displayName: "SCA (Dependency Check) Third Party Dependencies Analisys."
    inputs:
      projectName: 'MainHub.Internal.Internship.PeopleAndCulture'
      scanPath: '.'
      format: 'HTML'
      reportsDirectory: '$(Build.ArtifactStagingDirectory)/dependency-check'
      enableExperimental: true