//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainHub.Internal.PeopleAndCulture.TimesheetManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainHub.Internal.PeopleAndCulture.TimesheetManagement.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action by.
        /// </summary>
        public static string ActionBy {
            get {
                return ResourceManager.GetString("ActionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Date.
        /// </summary>
        public static string ActionDate {
            get {
                return ResourceManager.GetString("ActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet Activities added successfully!.
        /// </summary>
        public static string ActivitiesAdded {
            get {
                return ResourceManager.GetString("ActivitiesAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet Activities updated successfully!.
        /// </summary>
        public static string ActivitiesUpdated {
            get {
                return ResourceManager.GetString("ActivitiesUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Activity.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard Admin.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Menu.
        /// </summary>
        public static string AdminMenu {
            get {
                return ResourceManager.GetString("AdminMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Timesheets.
        /// </summary>
        public static string AllTimesheets {
            get {
                return ResourceManager.GetString("AllTimesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved/Rejected Date: .
        /// </summary>
        public static string ApprovalDate {
            get {
                return ResourceManager.GetString("ApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string ApprovalDateTable {
            get {
                return ResourceManager.GetString("ApprovalDateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved Timesheets.
        /// </summary>
        public static string ApprovedTimesheets {
            get {
                return ResourceManager.GetString("ApprovedTimesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Timesheet.
        /// </summary>
        public static string ApproveTimesheet {
            get {
                return ResourceManager.GetString("ApproveTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AreYouSUre {
            get {
                return ResourceManager.GetString("AreYouSUre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account.
        /// </summary>
        public static string ChangeAccount {
            get {
                return ResourceManager.GetString("ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Activities.
        /// </summary>
        public static string CreateActivities {
            get {
                return ResourceManager.GetString("CreateActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Timesheet.
        /// </summary>
        public static string CreateTimesheet {
            get {
                return ResourceManager.GetString("CreateTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The hours of a day must be between 0 and 24..
        /// </summary>
        public static string DayHours {
            get {
                return ResourceManager.GetString("DayHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click a timesheet to see details.
        /// </summary>
        public static string DoubleClick {
            get {
                return ResourceManager.GetString("DoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error approving the timesheet!.
        /// </summary>
        public static string ErrorApprovingTimesheet {
            get {
                return ResourceManager.GetString("ErrorApprovingTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error rejecting the timesheet!.
        /// </summary>
        public static string ErrorRejectingTimesheet {
            get {
                return ResourceManager.GetString("ErrorRejectingTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error submitting the timesheet!.
        /// </summary>
        public static string ErrorSubmittingTimesheet {
            get {
                return ResourceManager.GetString("ErrorSubmittingTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🕝 History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was invalid.
        /// </summary>
        public static string InvalidRequest {
            get {
                return ResourceManager.GetString("InvalidRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no Activities on this Timesheet yet..
        /// </summary>
        public static string NoActivities {
            get {
                return ResourceManager.GetString("NoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No activities data.
        /// </summary>
        public static string NoActivitiesData {
            get {
                return ResourceManager.GetString("NoActivitiesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved/Rejected Date: No action yet.
        /// </summary>
        public static string NoApprovalAction {
            get {
                return ResourceManager.GetString("NoApprovalAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this content..
        /// </summary>
        public static string NoContentAccess {
            get {
                return ResourceManager.GetString("NoContentAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Recent Actions.
        /// </summary>
        public static string NoRecentActions {
            get {
                return ResourceManager.GetString("NoRecentActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource.
        /// </summary>
        public static string NotAuthorizedResource {
            get {
                return ResourceManager.GetString("NotAuthorizedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No timesheet data.
        /// </summary>
        public static string NoTimesheetData {
            get {
                return ResourceManager.GetString("NoTimesheetData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have any timesheets yet..
        /// </summary>
        public static string NoTimesheets {
            get {
                return ResourceManager.GetString("NoTimesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possibly there are no drafts. Please try adding some.
        /// </summary>
        public static string PossiblyNoDrafts {
            get {
                return ResourceManager.GetString("PossiblyNoDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered by.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        public static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Timesheet.
        /// </summary>
        public static string RejectTimesheet {
            get {
                return ResourceManager.GetString("RejectTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Project, an Activity, a Type, and at least one day..
        /// </summary>
        public static string SelectActivities {
            get {
                return ResourceManager.GetString("SelectActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status:.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string StatusTable {
            get {
                return ResourceManager.GetString("StatusTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Date: .
        /// </summary>
        public static string SubmissionDate {
            get {
                return ResourceManager.GetString("SubmissionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission Date.
        /// </summary>
        public static string SubmissionDateTable {
            get {
                return ResourceManager.GetString("SubmissionDateTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted Timesheets.
        /// </summary>
        public static string SubmittedTimesheets {
            get {
                return ResourceManager.GetString("SubmittedTimesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to submit the timesheet?.
        /// </summary>
        public static string SubmitTheTimesheet {
            get {
                return ResourceManager.GetString("SubmitTheTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Timesheet.
        /// </summary>
        public static string SubmitTimesheet {
            get {
                return ResourceManager.GetString("SubmitTimesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string Surname {
            get {
                return ResourceManager.GetString("Surname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet.
        /// </summary>
        public static string Timesheet {
            get {
                return ResourceManager.GetString("Timesheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet Activities.
        /// </summary>
        public static string TimesheetActivities {
            get {
                return ResourceManager.GetString("TimesheetActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timesheet already exists for the current month and year..
        /// </summary>
        public static string TimesheetAlreadyExists {
            get {
                return ResourceManager.GetString("TimesheetAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet approved!.
        /// </summary>
        public static string TimesheetApproved {
            get {
                return ResourceManager.GetString("TimesheetApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A timesheet has been created..
        /// </summary>
        public static string TimesheetCreated {
            get {
                return ResourceManager.GetString("TimesheetCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet rejected!.
        /// </summary>
        public static string TimesheetRejected {
            get {
                return ResourceManager.GetString("TimesheetRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheets.
        /// </summary>
        public static string Timesheets {
            get {
                return ResourceManager.GetString("Timesheets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheets List.
        /// </summary>
        public static string TimesheetsList {
            get {
                return ResourceManager.GetString("TimesheetsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timesheet submitted!.
        /// </summary>
        public static string TimesheetSubmitted {
            get {
                return ResourceManager.GetString("TimesheetSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double click a timesheet for details.
        /// </summary>
        public static string ToolTip {
            get {
                return ResourceManager.GetString("ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Activities.
        /// </summary>
        public static string UpdateActivities {
            get {
                return ResourceManager.GetString("UpdateActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guid:.
        /// </summary>
        public static string UserGuid {
            get {
                return ResourceManager.GetString("UserGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Menu.
        /// </summary>
        public static string UserMenu {
            get {
                return ResourceManager.GetString("UserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Principal Name:.
        /// </summary>
        public static string UserPrincipalName {
            get {
                return ResourceManager.GetString("UserPrincipalName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfile {
            get {
                return ResourceManager.GetString("UserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        public static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
