//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainHub.Internal.PeopleAndCulture.PeopleManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainHub.Internal.PeopleAndCulture.PeopleManagement.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account.
        /// </summary>
        public static string AccessDeniedButton {
            get {
                return ResourceManager.GetString("AccessDeniedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this content..
        /// </summary>
        public static string AccessDeniedText {
            get {
                return ResourceManager.GetString("AccessDeniedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a Collaborator.
        /// </summary>
        public static string AddCollaboratorButton2 {
            get {
                return ResourceManager.GetString("AddCollaboratorButton2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Observation.
        /// </summary>
        public static string AddObservation {
            get {
                return ResourceManager.GetString("AddObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Observation.
        /// </summary>
        public static string AddObservationButton {
            get {
                return ResourceManager.GetString("AddObservationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adress.
        /// </summary>
        public static string Adress {
            get {
                return ResourceManager.GetString("Adress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anniverseries.
        /// </summary>
        public static string Anniverseries {
            get {
                return ResourceManager.GetString("Anniverseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome To PeopleManagement.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be importing all collaborators from Azure. Are you sure you want to do that?.
        /// </summary>
        public static string AzureAlertAll {
            get {
                return ResourceManager.GetString("AzureAlertAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled Import.
        /// </summary>
        public static string AzureCancelImport {
            get {
                return ResourceManager.GetString("AzureCancelImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import.
        /// </summary>
        public static string AzureFail {
            get {
                return ResourceManager.GetString("AzureFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Azure.
        /// </summary>
        public static string AzureHomeButton {
            get {
                return ResourceManager.GetString("AzureHomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import All.
        /// </summary>
        public static string AzureImportAButton {
            get {
                return ResourceManager.GetString("AzureImportAButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be importing.
        /// </summary>
        public static string AzureImporting {
            get {
                return ResourceManager.GetString("AzureImporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Imports.
        /// </summary>
        public static string AzureImports {
            get {
                return ResourceManager.GetString("AzureImports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Selected.
        /// </summary>
        public static string AzureImportSButton {
            get {
                return ResourceManager.GetString("AzureImportSButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You will be importing selected collaborators from Azure. Are you sure you want to do that?.
        /// </summary>
        public static string AzureImportSelected {
            get {
                return ResourceManager.GetString("AzureImportSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Successfull.
        /// </summary>
        public static string AzureImportSuccessfull {
            get {
                return ResourceManager.GetString("AzureImportSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure List.
        /// </summary>
        public static string AzureList {
            get {
                return ResourceManager.GetString("AzureList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Imports Pending.
        /// </summary>
        public static string AzurePending {
            get {
                return ResourceManager.GetString("AzurePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string AzureSure {
            get {
                return ResourceManager.GetString("AzureSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure Import.
        /// </summary>
        public static string AzureTitle {
            get {
                return ResourceManager.GetString("AzureTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email is missing in order to import..
        /// </summary>
        public static string AzureValidation {
            get {
                return ResourceManager.GetString("AzureValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Birthdays.
        /// </summary>
        public static string BirthdaysHomeButton {
            get {
                return ResourceManager.GetString("BirthdaysHomeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Birthdays.
        /// </summary>
        public static string BirthdaysTitle {
            get {
                return ResourceManager.GetString("BirthdaysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Number.
        /// </summary>
        public static string CCNumber {
            get {
                return ResourceManager.GetString("CCNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CC Valid Until.
        /// </summary>
        public static string CCValid {
            get {
                return ResourceManager.GetString("CCValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Date.
        /// </summary>
        public static string ChangeDate {
            get {
                return ResourceManager.GetString("ChangeDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed By.
        /// </summary>
        public static string ChangedBy {
            get {
                return ResourceManager.GetString("ChangedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Civil Status.
        /// </summary>
        public static string CivilStatus {
            get {
                return ResourceManager.GetString("CivilStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborator.
        /// </summary>
        public static string Collaborator {
            get {
                return ResourceManager.GetString("Collaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string CollaboratorAddButtonHome {
            get {
                return ResourceManager.GetString("CollaboratorAddButtonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborator History.
        /// </summary>
        public static string CollaboratorHistoryTitle {
            get {
                return ResourceManager.GetString("CollaboratorHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborators List.
        /// </summary>
        public static string CollaboratorsList {
            get {
                return ResourceManager.GetString("CollaboratorsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collaborators.
        /// </summary>
        public static string CollaboratorsName {
            get {
                return ResourceManager.GetString("CollaboratorsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string CollaboratorViewButtonHome {
            get {
                return ResourceManager.GetString("CollaboratorViewButtonHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Type.
        /// </summary>
        public static string ContractType {
            get {
                return ResourceManager.GetString("ContractType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created.
        /// </summary>
        public static string Created {
            get {
                return ResourceManager.GetString("Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Created Successfully.
        /// </summary>
        public static string CreatedSuccess {
            get {
                return ResourceManager.GetString("CreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created Successfully!.
        /// </summary>
        public static string CreatedSuccessfull {
            get {
                return ResourceManager.GetString("CreatedSuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Collaborator.
        /// </summary>
        public static string CreatedTitle {
            get {
                return ResourceManager.GetString("CreatedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to create..
        /// </summary>
        public static string CreatedUnsuccessfull {
            get {
                return ResourceManager.GetString("CreatedUnsuccessfull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation Date.
        /// </summary>
        public static string CreationDate {
            get {
                return ResourceManager.GetString("CreationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DeleteButton {
            get {
                return ResourceManager.GetString("DeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted By.
        /// </summary>
        public static string DeletedBy {
            get {
                return ResourceManager.GetString("DeletedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted Date.
        /// </summary>
        public static string DeletedDate {
            get {
                return ResourceManager.GetString("DeletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete.
        /// </summary>
        public static string DeleteFail {
            get {
                return ResourceManager.GetString("DeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Observation.
        /// </summary>
        public static string DeleteObservationButton {
            get {
                return ResourceManager.GetString("DeleteObservationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deleted successfully.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete User.
        /// </summary>
        public static string DeleteTitle {
            get {
                return ResourceManager.GetString("DeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependent Num.
        /// </summary>
        public static string DependentNum {
            get {
                return ResourceManager.GetString("DependentNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Contact.
        /// </summary>
        public static string EContact {
            get {
                return ResourceManager.GetString("EContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditButton {
            get {
                return ResourceManager.GetString("EditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Dates.
        /// </summary>
        public static string EmployeeDates {
            get {
                return ResourceManager.GetString("EmployeeDates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee Information.
        /// </summary>
        public static string EmployeeTitle {
            get {
                return ResourceManager.GetString("EmployeeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Date.
        /// </summary>
        public static string EntryDate {
            get {
                return ResourceManager.GetString("EntryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit Date.
        /// </summary>
        public static string ExitDate {
            get {
                return ResourceManager.GetString("ExitDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Exit Date.
        /// </summary>
        public static string ExitDateButton {
            get {
                return ResourceManager.GetString("ExitDateButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string F_Name {
            get {
                return ResourceManager.GetString("F_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed action.
        /// </summary>
        public static string FailedAction {
            get {
                return ResourceManager.GetString("FailedAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiscal Information.
        /// </summary>
        public static string FiscalInformation {
            get {
                return ResourceManager.GetString("FiscalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Collaborator.
        /// </summary>
        public static string ImportCollaborator {
            get {
                return ResourceManager.GetString("ImportCollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Deleted.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string L_Name {
            get {
                return ResourceManager.GetString("L_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading AzureAD.
        /// </summary>
        public static string LoadingAD {
            get {
                return ResourceManager.GetString("LoadingAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Birthdays ....
        /// </summary>
        public static string LoadingBirthdays {
            get {
                return ResourceManager.GetString("LoadingBirthdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Collaborators ....
        /// </summary>
        public static string LoadingCollaborators {
            get {
                return ResourceManager.GetString("LoadingCollaborators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locality.
        /// </summary>
        public static string Locality {
            get {
                return ResourceManager.GetString("Locality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Page.
        /// </summary>
        public static string MainPage {
            get {
                return ResourceManager.GetString("MainPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My ID.
        /// </summary>
        public static string MyID {
            get {
                return ResourceManager.GetString("MyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no birthdays in the next 7 days.
        /// </summary>
        public static string NoAnniverseries {
            get {
                return ResourceManager.GetString("NoAnniverseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Contact.
        /// </summary>
        public static string NoContact {
            get {
                return ResourceManager.GetString("NoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Date.
        /// </summary>
        public static string NoDate {
            get {
                return ResourceManager.GetString("NoDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to has no History.
        /// </summary>
        public static string NoHistory {
            get {
                return ResourceManager.GetString("NoHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No History.
        /// </summary>
        public static string NoHistoryTitle {
            get {
                return ResourceManager.GetString("NoHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no more information about this user.
        /// </summary>
        public static string NoInfo {
            get {
                return ResourceManager.GetString("NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information.
        /// </summary>
        public static string NoInfoTitle {
            get {
                return ResourceManager.GetString("NoInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no observations for this user. Do you want to add one?.
        /// </summary>
        public static string NoObservation {
            get {
                return ResourceManager.GetString("NoObservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Observation.
        /// </summary>
        public static string NoObservationTitle {
            get {
                return ResourceManager.GetString("NoObservationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observation Deleted Successfully.
        /// </summary>
        public static string ObservationDeleted {
            get {
                return ResourceManager.GetString("ObservationDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observations.
        /// </summary>
        public static string ObservationsButton {
            get {
                return ResourceManager.GetString("ObservationsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        public static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Observation.
        /// </summary>
        public static string SaveObservationButton {
            get {
                return ResourceManager.GetString("SaveObservationButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search collaborator.
        /// </summary>
        public static string SearchPlaceHolder {
            get {
                return ResourceManager.GetString("SearchPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Active.
        /// </summary>
        public static string SeeActiveButton {
            get {
                return ResourceManager.GetString("SeeActiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All.
        /// </summary>
        public static string SeeAllButton {
            get {
                return ResourceManager.GetString("SeeAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Inactive.
        /// </summary>
        public static string SeeInactiveButton {
            get {
                return ResourceManager.GetString("SeeInactiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOutButton {
            get {
                return ResourceManager.GetString("SignOutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SS Number.
        /// </summary>
        public static string SSNumber {
            get {
                return ResourceManager.GetString("SSNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string SubmitButton {
            get {
                return ResourceManager.GetString("SubmitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today!.
        /// </summary>
        public static string TableDays {
            get {
                return ResourceManager.GetString("TableDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Until.
        /// </summary>
        public static string TableDaysUntil {
            get {
                return ResourceManager.GetString("TableDaysUntil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string TableName {
            get {
                return ResourceManager.GetString("TableName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Number.
        /// </summary>
        public static string TaxNumber {
            get {
                return ResourceManager.GetString("TaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click to view collaborator details.
        /// </summary>
        public static string Tooltip {
            get {
                return ResourceManager.GetString("Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again later.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to update collaborator.
        /// </summary>
        public static string UpdateFail {
            get {
                return ResourceManager.GetString("UpdateFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updated successfully.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated user.
        /// </summary>
        public static string UpdateTitle {
            get {
                return ResourceManager.GetString("UpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID.
        /// </summary>
        public static string UserID {
            get {
                return ResourceManager.GetString("UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name, Last Name and Email are mandatory.
        /// </summary>
        public static string ValidationAlert {
            get {
                return ResourceManager.GetString("ValidationAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
