//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MainHub.Internal.PeopleAndCulture.AbsentManagement.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MainHub.Internal.PeopleAndCulture.AbsentManagement.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Start.
        /// </summary>
        public static string Absence_Start {
            get {
                return ResourceManager.GetString("Absence Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence approved!.
        /// </summary>
        public static string AbsenceApproved {
            get {
                return ResourceManager.GetString("AbsenceApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence canceleted to draft!.
        /// </summary>
        public static string AbsenceCanceleted {
            get {
                return ResourceManager.GetString("AbsenceCanceleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence deleted!.
        /// </summary>
        public static string AbsenceDeleted {
            get {
                return ResourceManager.GetString("AbsenceDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Details.
        /// </summary>
        public static string AbsenceDetails {
            get {
                return ResourceManager.GetString("AbsenceDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence End.
        /// </summary>
        public static string AbsenceEnd {
            get {
                return ResourceManager.GetString("AbsenceEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Of.
        /// </summary>
        public static string AbsenceOf {
            get {
                return ResourceManager.GetString("AbsenceOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence rejected!.
        /// </summary>
        public static string AbsenceRejected {
            get {
                return ResourceManager.GetString("AbsenceRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Saved!.
        /// </summary>
        public static string AbsenceSaved {
            get {
                return ResourceManager.GetString("AbsenceSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absences List.
        /// </summary>
        public static string AbsencesList {
            get {
                return ResourceManager.GetString("AbsencesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Start.
        /// </summary>
        public static string AbsenceStart {
            get {
                return ResourceManager.GetString("AbsenceStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence submitted!.
        /// </summary>
        public static string AbsenceSubmitted {
            get {
                return ResourceManager.GetString("AbsenceSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Type.
        /// </summary>
        public static string AbsenceType {
            get {
                return ResourceManager.GetString("AbsenceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Updated!.
        /// </summary>
        public static string AbsenceUpdated {
            get {
                return ResourceManager.GetString("AbsenceUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have access to this content..
        /// </summary>
        public static string AccessDeniedDetailed {
            get {
                return ResourceManager.GetString("AccessDeniedDetailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action By.
        /// </summary>
        public static string ActionBy {
            get {
                return ResourceManager.GetString("ActionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Date.
        /// </summary>
        public static string ActionDate {
            get {
                return ResourceManager.GetString("ActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action History.
        /// </summary>
        public static string ActionHistory {
            get {
                return ResourceManager.GetString("ActionHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Board.
        /// </summary>
        public static string AdminBoard {
            get {
                return ResourceManager.GetString("AdminBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Dashboard.
        /// </summary>
        public static string AdminDashboard {
            get {
                return ResourceManager.GetString("AdminDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Menu.
        /// </summary>
        public static string AdminMenu {
            get {
                return ResourceManager.GetString("AdminMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All drafts submitted.
        /// </summary>
        public static string AllDraftsSubmitted {
            get {
                return ResourceManager.GetString("AllDraftsSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All time.
        /// </summary>
        public static string Alltime {
            get {
                return ResourceManager.GetString("Alltime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on an absence to view info.
        /// </summary>
        public static string AllUserCalendarHelp {
            get {
                return ResourceManager.GetString("AllUserCalendarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Users Calendar.
        /// </summary>
        public static string AllUsersCalendar {
            get {
                return ResourceManager.GetString("AllUsersCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is already an absence in that period.
        /// </summary>
        public static string AlreadyAnAbsence {
            get {
                return ResourceManager.GetString("AlreadyAnAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval.
        /// </summary>
        public static string Approval {
            get {
                return ResourceManager.GetString("Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Date.
        /// </summary>
        public static string ApprovalDate {
            get {
                return ResourceManager.GetString("ApprovalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval Status.
        /// </summary>
        public static string ApprovalStatus {
            get {
                return ResourceManager.GetString("ApprovalStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approval ✅.
        /// </summary>
        public static string ApprovalWithEmojii {
            get {
                return ResourceManager.GetString("ApprovalWithEmojii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string ApprovedBy {
            get {
                return ResourceManager.GetString("ApprovedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string Areyousure {
            get {
                return ResourceManager.GetString("Areyousure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        public static string Calendar {
            get {
                return ResourceManager.GetString("Calendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar.
        /// </summary>
        public static string CalendarCapsOff {
            get {
                return ResourceManager.GetString("CalendarCapsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save as draft or submit absence =&gt; Click on a blank slot.
        /// </summary>
        public static string CalendarHelp {
            get {
                return ResourceManager.GetString("CalendarHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar 🗓.
        /// </summary>
        public static string CalendarView {
            get {
                return ResourceManager.GetString("CalendarView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Absence (to Draft).
        /// </summary>
        public static string CancelAbsenceToDraft {
            get {
                return ResourceManager.GetString("CancelAbsenceToDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Account.
        /// </summary>
        public static string ChangeAccount {
            get {
                return ResourceManager.GetString("ChangeAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click for more info.
        /// </summary>
        public static string ClickDetails {
            get {
                return ResourceManager.GetString("ClickDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string Dark {
            get {
                return ResourceManager.GetString("Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string DashBoard {
            get {
                return ResourceManager.GetString("DashBoard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence Date must be in the future..
        /// </summary>
        public static string DateMustBeInFuture {
            get {
                return ResourceManager.GetString("DateMustBeInFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Absence.
        /// </summary>
        public static string DeleteAbsence {
            get {
                return ResourceManager.GetString("DeleteAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Click the item for Info.
        /// </summary>
        public static string DoubleClickDetails {
            get {
                return ResourceManager.GetString("DoubleClickDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft.
        /// </summary>
        public static string Draft {
            get {
                return ResourceManager.GetString("Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to draft.
        /// </summary>
        public static string DraftCapsOff {
            get {
                return ResourceManager.GetString("DraftCapsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drafts.
        /// </summary>
        public static string Drafts {
            get {
                return ResourceManager.GetString("Drafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Absence.
        /// </summary>
        public static string EditAbsence {
            get {
                return ResourceManager.GetString("EditAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date.
        /// </summary>
        public static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR approving absence!.
        /// </summary>
        public static string ErrorApproving {
            get {
                return ResourceManager.GetString("ErrorApproving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR canceling absence!.
        /// </summary>
        public static string ErrorCanceling {
            get {
                return ResourceManager.GetString("ErrorCanceling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR deleting absence!.
        /// </summary>
        public static string ErrorDeleting {
            get {
                return ResourceManager.GetString("ErrorDeleting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error processing your request. Please try again later..
        /// </summary>
        public static string ErrorProcessing {
            get {
                return ResourceManager.GetString("ErrorProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ERROR rejecting absence!.
        /// </summary>
        public static string ErrorRejecting {
            get {
                return ResourceManager.GetString("ErrorRejecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating.
        /// </summary>
        public static string ErrorUpdating {
            get {
                return ResourceManager.GetString("ErrorUpdating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Calendar.
        /// </summary>
        public static string GlobalCalendar {
            get {
                return ResourceManager.GetString("GlobalCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Calendar 🗓.
        /// </summary>
        public static string GlobalCalendarWithEmojii {
            get {
                return ResourceManager.GetString("GlobalCalendarWithEmojii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string Light {
            get {
                return ResourceManager.GetString("Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Absences 📋.
        /// </summary>
        public static string ListView {
            get {
                return ResourceManager.GetString("ListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Absences.
        /// </summary>
        public static string MyAbsences {
            get {
                return ResourceManager.GetString("MyAbsences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Absences List.
        /// </summary>
        public static string MyAbsencesList {
            get {
                return ResourceManager.GetString("MyAbsencesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Calendar.
        /// </summary>
        public static string MyCalendar {
            get {
                return ResourceManager.GetString("MyCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next week Approved Absences.
        /// </summary>
        public static string NextWeek {
            get {
                return ResourceManager.GetString("NextWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No absence data.
        /// </summary>
        public static string NoAbsenceData {
            get {
                return ResourceManager.GetString("NoAbsenceData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Data Found.
        /// </summary>
        public static string NoDataFound {
            get {
                return ResourceManager.GetString("NoDataFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Info.
        /// </summary>
        public static string NoInfo {
            get {
                return ResourceManager.GetString("NoInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information.
        /// </summary>
        public static string NoInformation {
            get {
                return ResourceManager.GetString("NoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Recent Actions.
        /// </summary>
        public static string NoRecentActions {
            get {
                return ResourceManager.GetString("NoRecentActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Approved.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Submitted.
        /// </summary>
        public static string NotSubmitted {
            get {
                return ResourceManager.GetString("NotSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no more information about this user.
        /// </summary>
        public static string NoUserInfo {
            get {
                return ResourceManager.GetString("NoUserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is only accepted to add an absence from the current year.
        /// </summary>
        public static string OnlyAcceptedFromThisYear {
            get {
                return ResourceManager.GetString("OnlyAcceptedFromThisYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People.
        /// </summary>
        public static string People {
            get {
                return ResourceManager.GetString("People", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to People 👨.
        /// </summary>
        public static string PeopleWithEmojii {
            get {
                return ResourceManager.GetString("PeopleWithEmojii", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person.
        /// </summary>
        public static string Person {
            get {
                return ResourceManager.GetString("Person", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an absence type.
        /// </summary>
        public static string PleaseSelectType {
            get {
                return ResourceManager.GetString("PleaseSelectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possibly there are no drafts. Please try adding some.
        /// </summary>
        public static string PossiblyThereAreNoDrafts {
            get {
                return ResourceManager.GetString("PossiblyThereAreNoDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Powered By.
        /// </summary>
        public static string PoweredBy {
            get {
                return ResourceManager.GetString("PoweredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Information.
        /// </summary>
        public static string ProfileInformation {
            get {
                return ResourceManager.GetString("ProfileInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Absence.
        /// </summary>
        public static string RejectAbsence {
            get {
                return ResourceManager.GetString("RejectAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Rejected {
            get {
                return ResourceManager.GetString("Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Absence.
        /// </summary>
        public static string RequestAbsence {
            get {
                return ResourceManager.GetString("RequestAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restricted.
        /// </summary>
        public static string Restricted {
            get {
                return ResourceManager.GetString("Restricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Absence.
        /// </summary>
        public static string SaveAbsence {
            get {
                return ResourceManager.GetString("SaveAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Draft.
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you want also to save drafts, please use the.
        /// </summary>
        public static string SaveDraftDetails {
            get {
                return ResourceManager.GetString("SaveDraftDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search collaborator.
        /// </summary>
        public static string Searchcollaborator {
            get {
                return ResourceManager.GetString("Searchcollaborator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Active.
        /// </summary>
        public static string SeeActive {
            get {
                return ResourceManager.GetString("SeeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See All.
        /// </summary>
        public static string SeeAll {
            get {
                return ResourceManager.GetString("SeeAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See Inactive.
        /// </summary>
        public static string SeeInactive {
            get {
                return ResourceManager.GetString("SeeInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Error.
        /// </summary>
        public static string ServerError {
            get {
                return ResourceManager.GetString("ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date must be before end date..
        /// </summary>
        public static string StartDateMust {
            get {
                return ResourceManager.GetString("StartDateMust", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status_ {
            get {
                return ResourceManager.GetString("Status:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submission.
        /// </summary>
        public static string Submission {
            get {
                return ResourceManager.GetString("Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Absence.
        /// </summary>
        public static string SubmitAbsence {
            get {
                return ResourceManager.GetString("SubmitAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit All Drafts.
        /// </summary>
        public static string SubmitAllDrafts {
            get {
                return ResourceManager.GetString("SubmitAllDrafts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On this page you can submit absences..
        /// </summary>
        public static string SubmitDetails {
            get {
                return ResourceManager.GetString("SubmitDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submitted.
        /// </summary>
        public static string Submitted {
            get {
                return ResourceManager.GetString("Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surname:.
        /// </summary>
        public static string Surname_ {
            get {
                return ResourceManager.GetString("Surname:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme 🎨.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The request was invalid.
        /// </summary>
        public static string TheRequestWasInvalid {
            get {
                return ResourceManager.GetString("TheRequestWasInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will save your absence as.
        /// </summary>
        public static string ThisWillSaveYourAbsenceAs {
            get {
                return ResourceManager.GetString("ThisWillSaveYourAbsenceAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown Eror.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Guid.
        /// </summary>
        public static string UserGuid {
            get {
                return ResourceManager.GetString("UserGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Menu.
        /// </summary>
        public static string UserMenu {
            get {
                return ResourceManager.GetString("UserMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Principal Name:.
        /// </summary>
        public static string UserPrincipalName_ {
            get {
                return ResourceManager.GetString("UserPrincipalName:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Absence.
        /// </summary>
        public static string ViewAbsence {
            get {
                return ResourceManager.GetString("ViewAbsence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View History.
        /// </summary>
        public static string ViewHistory {
            get {
                return ResourceManager.GetString("ViewHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Absence interval must be at least 1 hour..
        /// </summary>
        public static string WrongAbsenceInterval {
            get {
                return ResourceManager.GetString("WrongAbsenceInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong hours for Afternoon absence.
        /// </summary>
        public static string WrongHoursForAfternoon {
            get {
                return ResourceManager.GetString("WrongHoursForAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong hours for Full Day absence.
        /// </summary>
        public static string WrongHoursForFullDay {
            get {
                return ResourceManager.GetString("WrongHoursForFullDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong hours for Morning absence.
        /// </summary>
        public static string WrongHoursForMorning {
            get {
                return ResourceManager.GetString("WrongHoursForMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not authorized to access this resource.
        /// </summary>
        public static string YouAreNotAuthorized {
            get {
                return ResourceManager.GetString("YouAreNotAuthorized", resourceCulture);
            }
        }
    }
}
